#!/bin/sh

set -e -x

# Kernel Source
KERNEL_SOURCE=https://github.com/lazycodebuilder/kernel_r3p_recovery
KERNEL_BRANCH=14
KERNEL_DEFCONFIG=sdm670-perf_defconfig

# Prebuilt Proton Clang Toolchain
CLANG=https://github.com/kdrag0n/proton-clang.git
CLANG_BRANCH=master

# Setup make Command
make_fun() {
  make O=out ARCH=arm64 CC=clang \
       LLVM=1 LLVM_IAS=1 \
       CROSS_COMPILE=aarch64-linux-gnu- \
       CROSS_COMPILE_ARM32=arm-linux-gnueabi- "$@"
}

# Work Path
WORK=${HOME}/work

# Kernel Folder Name
KERNEL=android-kernel

# Kernel Source Path
KERNEL_SRC=${WORK}/${KERNEL}

# Prepare Directory
mkdir -p "${WORK}"
cd "${WORK}" || exit 1

# Cloning all the Necessary files
[ ! -d clang ] && git clone --depth=1 "${CLANG}" -b "${CLANG_BRANCH}" ./clang
[ ! -d "${KERNEL}" ] && git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"

# Setting Toolchain Path
PATH="${WORK}/clang/bin:$PATH"

# Enter Kernel root directory
cd "${KERNEL_SRC}" || exit 1

# Start Compiling Kernel
make_fun "${KERNEL_DEFCONFIG}"
make_fun -j"$(nproc --all)" 2>&1 | tee build.log || exit 1
